apiVersion: v1
kind: Service
metadata:
  name: ibm-ansible-demo-svc
spec:
  type: NodePort
  selector:
    app: ibm-ansible-demo
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081
